#Workflow name
name: Dispatch app to Github Artifacts
run-name: Deploy by @${{ github.actor }}

#Generating triggers: It only triggers when push is generated on master branch.
on:
  push:
    branches: [ master ]

#Generating jobs: Execute job when trigger is hit.
jobs:
  app-utils-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Upload API Key to gradle properties 🔥
        run: sed -i "s|PIXABAY_KEY|${{secrets.PIXABAY_KEY}}|g" ./gradle.properties


  #Generate an apk
  build-apk:
    needs: app-utils-creation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Cache Android Dependencies
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/lib/android/sdk
            /usr/local/lib/android/ndk
          key: android-dependencies-${{ runner.os }}

      - name: Install Android NDK and SDK
        run: |
          # Install Android NDK
          wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip -d /usr/local/lib/android
          rm android-ndk-r21e-linux-x86_64.zip
          
          # Install Android SDK (adjust the URL as needed)
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip -q commandlinetools-linux-7302050_latest.zip -d /usr/local/lib/android
          rm commandlinetools-linux-7302050_latest.zip
          
          # Add Android SDK tools/bin to PATH
          echo 'export PATH=$PATH:/usr/local/lib/android/cmdline-tools/latest/bin' >> $HOME/.bashrc
        shell: bash

      - name: Build APK with CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=23 -DANDROID_PLATFORM=android-23 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/usr/local/lib/android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../app/build/intermediates/cxx/Debug/3u3q2259/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../app/build/intermediates/cxx/Debug/3u3q2259/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
        working-directory: ${{ github.workspace }}/app

      - name: Build debuging APK 🔥
        run: bash ./gradlew assembleDebug

      - name: Uploading APK to Github Artifacts 🚀
        uses: actions/upload-artifact@v3
        with:
          name: $APK_NAME
          path: app/build/outputs/apk/debug/$APK_NAME
        env:
          APK_NAME: "app-debug.apk"
